--- #YAML:1.0
name: Test-MockRandom
version: 0.91
author: ~
abstract: |-
  Replaces random number generation with non-random number
  generation
license: perl
build_requires:
  Test::Exception: 0.19
  Test::Simple: 0.53
provides:
  Test::MockRandom:
    file: lib/Test/MockRandom.pm
    version: 0.91
generated_by: Module::Build version 0.2606
