---
name: Test-MockRandom
version: 0.96
author:
  - David A Golden <dagolden@cpan.org>
abstract: |-
  Replaces random number generation with non-random number
  generation
license: perl
requires:
  perl: 5.005
build_requires:
  Test::Exception: 0.2
  Test::More: 0.6
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
provides:
  Test::MockRandom:
    file: lib/Test/MockRandom.pm
    version: 0.96
generated_by: Module::Build version 0.2608
